<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DatabaseConnectionTECOMNET</RootNamespace>
    <TargetFramework>net4.8</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModelsTECOMNET\ModelsTECOMNET.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
