Public Class DescriptionsController
    Inherits Controller

    Function Descriptions(ByVal Tipo As String) As ActionResult
        ViewData("Title") = "Descriptions"
        Dim objDescription As New DescriptionModel
        Select Case Tipo
            Case "SIMSACTIVOS"
                objDescription.Tipo = "POST"
                objDescription.Metodo = "Batch_Obtener_SIMS_Activos"
                objDescription.Descripcion = "Permite obtener un archivo CSV plano con la información de los SIMS activos."
                objDescription.Nota = "La información obtenida refleja los movimientos del día anterior, se actualiza cada 24."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/BYD/ObtenerSIMs/Activos"
                objDescription.Color = "badge bg-success"
                objDescription.HeaderVisible = ""
                objDescription.HeaderVisibleLogin = "none"
                objDescription.ResponseType = "CSV"
                objDescription.ResponseDescription = "MSISDN|VIN|Producto|Expira|MegasAsignados|ConsumoEnMB|MegasDisponibles|MegasAdicionales"
            Case "SIMSINACTIVOS"
                objDescription.Tipo = "POST"
                objDescription.Metodo = "Batch_Obtener_SIMS_Inactivos"
                objDescription.Descripcion = "Permite obtener un archivo CSV plano con la información de los SIMS inactivos."
                objDescription.Nota = "La información obtenida refleja los movimientos del día anterior, se actualiza cada 24."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/BYD/ObtenerSIMs/Inactivos"
                objDescription.Color = "badge bg-success"
                objDescription.HeaderVisible = ""
                objDescription.HeaderVisibleLogin = "none"
                objDescription.ResponseType = "CSV"
                objDescription.ResponseDescription = "MSISDN|VIN|Producto|Expira|MegasAsignados|ConsumoEnMB|MegasDisponibles|MegasAdicionales|FechaDeBaja"
            Case "VEHICULOSACTIVOS"
                objDescription.Tipo = "POST"
                objDescription.Metodo = "Batch_Obtener_Vehículos_Activos"
                objDescription.Descripcion = "Permite obtener un archivo CSV plano con la información de los vehículos activos."
                objDescription.Nota = "La información obtenida refleja los movimientos del día anterior, se actualiza cada 24."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/BYD/ObtenerVehiculos/Activos"
                objDescription.Color = "badge bg-success"
                objDescription.HeaderVisible = ""
                objDescription.HeaderVisibleLogin = "none"
                objDescription.ResponseType = "CSV"
                objDescription.ResponseDescription = "Modelo|VIN|Year|FechaAlta"
            Case "VEHICULOSINACTIVOS"
                objDescription.Tipo = "POST"
                objDescription.Metodo = "Batch_Obtener_Vehículos_Inactivos"
                objDescription.Descripcion = "Permite obtener un archivo CSV plano con la información de los vehículos inactivos."
                objDescription.Nota = "La información obtenida refleja los movimientos del día anterior, se actualiza cada 24."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/BYD/ObtenerVehiculos/Inactivos"
                objDescription.Color = "badge bg-success"
                objDescription.HeaderVisible = ""
                objDescription.HeaderVisibleLogin = "none"
                objDescription.ResponseType = "CSV"
                objDescription.ResponseDescription = "Modelo|VIN|Year|FechaDeAlta|FechaDeBaja"
            Case "CLIENTESACTIVOS"
                objDescription.Tipo = "POST"
                objDescription.Metodo = "Batch_Obtener_Clientes_Activos"
                objDescription.Descripcion = "Permite obtener un archivo CSV plano con la información de los clientes activos."
                objDescription.Nota = "La información obtenida refleja los movimientos del día anterior, se actualiza cada 24."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/BYD/ObtenerClientes/Activos"
                objDescription.Color = "badge bg-success"
                objDescription.HeaderVisible = ""
                objDescription.HeaderVisibleLogin = "none"
                objDescription.ResponseType = "CSV"
                objDescription.ResponseDescription = "Nombre|FechaDeCumpleaños|FechaDeAlta|PAIS|Estado"
            Case "CLIENTESINACTIVOS"
                objDescription.Tipo = "POST"
                objDescription.Metodo = "Batch_Obtener_Clientes_Inactivos"
                objDescription.Descripcion = "Permite obtener un archivo CSV plano con la información de los clientes inactivos."
                objDescription.Nota = "La información obtenida refleja los movimientos del día anterior, se actualiza cada 24."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/BYD/ObtenerClientes/Inactivos"
                objDescription.Color = "badge bg-success"
                objDescription.HeaderVisible = ""
                objDescription.HeaderVisibleLogin = "none"
                objDescription.ResponseType = "CSV"
                objDescription.ResponseDescription = "Nombre|FechaDeCumpleaños|FechaDeAlta|PAIS|Estado|FechaDeBaja"
            Case "RECARGAS"
                objDescription.Tipo = "POST"
                objDescription.Metodo = "Batch_Obtener_Recargas"
                objDescription.Descripcion = "Permite obtener un archivo CSV plano con la información de las recargas, utiliza un filtro de fechas."
                objDescription.Nota = "La información obtenida refleja los movimientos en tiempo real."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/BYD/ObtenerRecargas/Desde/2025-02-01/Hasta/2025-02-28"
                objDescription.Color = "badge bg-success"
                objDescription.HeaderVisible = ""
                objDescription.HeaderVisibleLogin = "none"
                objDescription.ResponseType = "CSV"
                objDescription.ResponseDescription = "Modelo|Paquete|DiaDeCompra|MEGAS|FormaDePago"
            Case "PERFIL"
                objDescription.Tipo = "GET"
                objDescription.Metodo = "Consulta_de_perfil_de_UF"
                objDescription.Descripcion = "Esta operación permite consultar el perfil de un usuario final por medio de su MSISDN."
                objDescription.Nota = "La información obtenida refleja los datos en tiempo real, el servicio puede ser bloqueado por alta demanda."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/BYD/ObtenerPerfil/5584616246"
                objDescription.Color = "badge bg-primary"
                objDescription.HeaderVisible = ""
                objDescription.HeaderVisibleLogin = "none"
                objDescription.ResponseType = "JSON"
                objDescription.ResponseDescription = "{ICCID: 8952140063551098927,IMEI: 86322506017261,subStatus: Active,totalAmt: 13000, unusedAmt: 12999,expireDate: 20250401000000,APN: iot,estatusAPN: activo}"
            Case "TOKEN"
                objDescription.Tipo = "POST"
                objDescription.Metodo = "Generación_de_Token"
                objDescription.Descripcion = "Esta operación permite generar un token que se utilizará para consumir el resto de los recursos."
                objDescription.Nota = "Las credenciales serán proporcionadas vía solitud correo electrónico a nuestra área comercial."
                objDescription.ResourceURL = "https://tecomnet.net/TECOMNET/APIDeveloper/api/Account"
                objDescription.Color = "badge bg-success"
                objDescription.HeaderVisible = "none"
                objDescription.HeaderVisibleLogin = ""
                objDescription.ResponseType = "Text"
                objDescription.ResponseDescription = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlVzZ.."
        End Select

        Return View(objDescription)

    End Function
End Class